/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MarketWeatherRouteImport } from './routes/market-weather'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as CropDiagnosisIndexRouteImport } from './routes/crop-diagnosis.index'
import { Route as CropDiagnosisResultRouteImport } from './routes/crop-diagnosis.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketWeatherRoute = MarketWeatherRouteImport.update({
  id: '/market-weather',
  path: '/market-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CropDiagnosisIndexRoute = CropDiagnosisIndexRouteImport.update({
  id: '/crop-diagnosis/',
  path: '/crop-diagnosis/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropDiagnosisResultRoute = CropDiagnosisResultRouteImport.update({
  id: '/crop-diagnosis/result',
  path: '/crop-diagnosis/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/market-weather': typeof MarketWeatherRoute
  '/settings': typeof SettingsRoute
  '/community/$id': typeof CommunityIdRoute
  '/crop-diagnosis/result': typeof CropDiagnosisResultRoute
  '/community/': typeof CommunityIndexRoute
  '/crop-diagnosis/': typeof CropDiagnosisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/market-weather': typeof MarketWeatherRoute
  '/settings': typeof SettingsRoute
  '/community/$id': typeof CommunityIdRoute
  '/crop-diagnosis/result': typeof CropDiagnosisResultRoute
  '/community': typeof CommunityIndexRoute
  '/crop-diagnosis': typeof CropDiagnosisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/market-weather': typeof MarketWeatherRoute
  '/settings': typeof SettingsRoute
  '/community/$id': typeof CommunityIdRoute
  '/crop-diagnosis/result': typeof CropDiagnosisResultRoute
  '/community/': typeof CommunityIndexRoute
  '/crop-diagnosis/': typeof CropDiagnosisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/dashboard'
    | '/history'
    | '/market-weather'
    | '/settings'
    | '/community/$id'
    | '/crop-diagnosis/result'
    | '/community/'
    | '/crop-diagnosis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/dashboard'
    | '/history'
    | '/market-weather'
    | '/settings'
    | '/community/$id'
    | '/crop-diagnosis/result'
    | '/community'
    | '/crop-diagnosis'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/dashboard'
    | '/history'
    | '/market-weather'
    | '/settings'
    | '/community/$id'
    | '/crop-diagnosis/result'
    | '/community/'
    | '/crop-diagnosis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  MarketWeatherRoute: typeof MarketWeatherRoute
  SettingsRoute: typeof SettingsRoute
  CommunityIdRoute: typeof CommunityIdRoute
  CropDiagnosisResultRoute: typeof CropDiagnosisResultRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CropDiagnosisIndexRoute: typeof CropDiagnosisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-weather': {
      id: '/market-weather'
      path: '/market-weather'
      fullPath: '/market-weather'
      preLoaderRoute: typeof MarketWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-diagnosis/': {
      id: '/crop-diagnosis/'
      path: '/crop-diagnosis'
      fullPath: '/crop-diagnosis/'
      preLoaderRoute: typeof CropDiagnosisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-diagnosis/result': {
      id: '/crop-diagnosis/result'
      path: '/crop-diagnosis/result'
      fullPath: '/crop-diagnosis/result'
      preLoaderRoute: typeof CropDiagnosisResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  MarketWeatherRoute: MarketWeatherRoute,
  SettingsRoute: SettingsRoute,
  CommunityIdRoute: CommunityIdRoute,
  CropDiagnosisResultRoute: CropDiagnosisResultRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CropDiagnosisIndexRoute: CropDiagnosisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
